project:
  type: website

website:
  title: "Leo's blog"
  navbar:
    right:
      - about.qmd
      - icon: linkedin
        href: https://www.linkedin.com/in/leo-kiernan-2ba2561a0/
      - icon: twitter
        href: https://twitter.com/DrLeo037
      - icon: Mastodon
        text: Mastodon
        href: https://fosstodon.org/@drleo037
  comments:
    giscus: 
      repo: drleo037/quarto-giscus
      repo-id: R_kgDOI8qETA
      category: Announcements
      category-id: DIC_kwDOI8qETM4CUJOL
      mapping: pathname
      input-position: top
      theme: light
      loading: lazy

format:
  html:
    theme: cosmo
    css: styles.css

editor: visual


